// Generated by CoffeeScript 1.7.1
(function() {
  var R;

  R = React.DOM;

  this.Greeter = React.createClass({
    getInitialState: function() {
      return {
        name: 'there'
      };
    },
    update: function(e) {
      return this.setState({
        name: e.target.value
      });
    },
    render: function() {
      return R.div({
        className: 'greeter'
      }, R.input({
        type: 'text',
        placeholder: 'What is your name?',
        onChange: this.update
      }), R.h1(null, "Hello, " + this.state.name + "!"));
    }
  });

  React.render(React.createElement(this.Greeter), document.body);

}).call(this);
