// Generated by CoffeeScript 1.7.1
(function() {
  this.Greetings = React.createClass({
    render: function() {
      return React.DOM.h2(null, 'Hello world');
    }
  });

  React.render(React.createElement(this.Greetings), document.body);

}).call(this);
